version: '3'
services:
    pg_db:
        container_name: todoApp
        image: postgres:10
        restart: always
        volumes:
            - postgres-data:/var/lib/postgres/todoApp/data
        env_file:
            - .env
        ports:
            - '5432:5432'
volumes:
    postgres-data:
